// Shared catalogue of commonly replaced automotive parts
// Used by EstimateCalculator (intake) and JobCardDetailsScreen (edit)

export const COMMON_PARTS = [
  'Engine Oil',
  'Oil Filter',
  'Air Filter',
  'Fuel Filter',
  'Cabin Air Filter',
  'Spark Plugs',
  'Brake Pads (Front)',
  'Brake Pads (Rear)',
  'Brake Disc (Front)',
  'Brake Disc (Rear)',
  'Brake Fluid',
  'Coolant / Antifreeze',
  'Transmission Fluid',
  'Power Steering Fluid',
  'Wiper Blades',
  'Battery',
  'Alternator Belt',
  'Timing Belt / Chain',
  'Clutch Plate',
  'Clutch Pressure Plate',
  'Radiator Hose',
  'Thermostat',
  'Water Pump',
  'Shock Absorber (Front)',
  'Shock Absorber (Rear)',
  'Ball Joint',
  'Tie Rod End',
  'CV Axle / Drive Shaft',
  'Wheel Bearing',
  'Headlight Bulb',
  'Tail Light Bulb',
  'Fog Light Bulb',
  'Horn',
  'Fuse',
  'Oxygen Sensor',
  'Throttle Body',
  'Fuel Pump',
  'Fuel Injector',
  'Mass Air Flow Sensor',
  'Exhaust Pipe',
  'Catalytic Converter',
  'AC Compressor',
  'AC Filter / Dryer',
  'AC Refrigerant (Gas)',
  'Radiator',
  'Fan Belt',
  'Idler Pulley',
  'Tensioner Pulley',
  'Windshield',
  'Door Glass',
  'Tyres (Set)',
  'Wheel Alignment & Balancing',
  'Custom Part', // always last — opens free-text input
];
